#!MC 1410
$!VarSet |MFBD| = './'
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!PAGE NAME = 'Untitled'
$!PAGECONTROL CREATE
$!PICK SETMOUSEMODE
  MOUSEMODE = SELECT
$!OPENLAYOUT  "|$layoutfile|"
$!PRINTSETUP PALETTE = COLOR
$!EXPORTSETUP IMAGEWIDTH = 1067
$!EXPORTSETUP EXPORTFNAME = '|$pngfilename|'
$!EXPORT
  EXPORTREGION = CURRENTFRAME
$!RemoveVar |MFBD|
